name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check application health for status code 2xx
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-part-11.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true