name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Extract last commit message
        run: |
          LAST_COMMIT_MESSAGE=$(jq -r '.[-1].message | split("\n")[0]' <<< '${{ toJson(github.event.commits) }}') &&
          echo "LAST_COMMIT_MESSAGE=$LAST_COMMIT_MESSAGE" >> $GITHUB_ENV
      - name: Check if last commit message contains "#skip"
        if: !contains(env.LAST_COMMIT_MESSAGE, '#skip')
        run: echo "'#skip' detected, skipping workflow"